name: Node.js CI
on:
  pull_request:
    types:
      - closed
  push:
    branches: [ "main" ]
env:
  AWS_REGION: "us-east-2"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm run test
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACC_ID}}:role/aws-next-report-access
          role-session-name: GitHub-Action-Role
          aws-region: us-east-2
      
      - name: Run commands on EC2
        id: run_commands
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":[${{secrets.PROD_INSTANCE_ID}}]}]' --parameters '{"commands":["sudo git config --global --add safe.directory /home/ubuntu/next-report-app","sudo pm2 delete next-report-app","sudo git pull","sudo npm install --legacy-peer-deps","sudo npm run build","sudo pm2 start npm --name next-report-app -- run start -- -p 3000"],"workingDirectory":["/home/ubuntu/next-report-app"],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --output-s3-bucket-name "lobbylinkablebucket" --region us-east-2

