name: Node.js CI
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: "us-east-2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACC_ID}}:role/aws-next-report-access
          role-session-name: GitHub-Action-Role
          aws-region: us-east-2
      
      - name: Run commands on EC2
        id: run_commands
        run: |
          aws sts get-caller-identity
          aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":["i-0e8c9bfb3c28e15ab"]}]' --parameters '{"commands":["cd next-report-app","git pull","npm install --legacy-peer-deps ","npm run build","pm2 kill","pm2 stop","pm2 start npm --name next-report-app -- run start -- -p 3000"],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 1000 --max-concurrency "50" --max-errors "0" --output-s3-bucket-name "lobbylinkablebucket" --region us-east-2
