name: Node.js CI
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: "us-east-2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
      - uses: peterkimzz/aws-ssm-send-command@main
        id: ssm
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACC_ID}}:role/aws-next-report-access
          role-session-name: GitHub-Action-Role
          aws-region: us-east-2
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          instance-ids: i-0e8c9bfb3c28e15ab

          working-directory: /home/ubuntu/next-report-app
          command: ls -al
          comment: Hello world!

      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
  