name: Node.js CI
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          ls
          aws ec2-instance-connect ssh --instance-id i-0e8c9bfb3c28e15ab
  