name: Node.js CI
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION: "us-east-2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACC_ID}}:role/aws-next-report-access
          role-session-name: GitHub-Action-Role
          aws-region: us-east-2
      
      - name: Run commands on EC2
        id: run_commands
        run: |
          COMMAND_ID=$(aws sts get-caller-identity
          aws ssm send-command \
              --instance-ids "i-0e8c9bfb3c28e15ab" \
              --document-name "AWS-RunShellScript" \
              --parameters 'commands=["cd home/ubuntu/next-report-app", "ls"]' \
              --query "Command.CommandId" \
              --output text \
              --comment "testing connection")

          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"    

      - name: Output command results
        id: output
        run: |
          sleep 15s
          COMMAND_ID=${{ steps.execute_command.outputs.command_id }}
          aws ssm list-command-invocations \
            --details \
            --instance-id i-0e8c9bfb3c28e15ab \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Output:Output}" \
            --command-id "$COMMAND_ID" \
            --output text


  
